services: 
  database:
    image: postgres:13-alpine
    environment:
        POSTGRES_DB: reminder
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Guieduda1731
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  reminder:
      build: .
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - database
      environment:
        DB_NAME: reminder
        DB_USER: postgres
        DB_PASSWORD: Guieduda1731
        DB_HOST: database
        DB_PORT: 5432

volumes:
  postgres_data: 